name: dispatch
on: repository_dispatch

jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event is '${{ github.event.action }}'" 
          echo "Message is '${{ github.event.client_payload.message }}'"