# This is a basic workflow to help you get started with Actions

name: dispatch

# Controls when the workflow will run
on: repository_dispatch
  # Triggers the workflow on push or pull request events but only for the main branch
  # repository_dispatch:
  #   types: [dispatch]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event is '${{ github.event.action }}'" 
          echo "Message is '${{ github.event.client_payload.message }}'"